### ISSUE TITLE
About updating data

### ISSUE THREAD

**Issue by jingyan-li** [arperyan/svelte-deckgl#5]
Hi I am trying to utilize the Deckgl component to visualize some data in svelte. But I am not sure whether the component can handle updateTriggers in Deck.gl. Do you have any ideas about how to add this into the current component?

Thank you!

**Comment by arperyan** [comment]
Hi,

I haven't looked at this in months. I will have a look tomorrow and see if I am able to help.

Ryan

**Comment by arperyan** [comment]
Hi @jingyan-li ,

I created a simple version which allows me to update the data via an input. In the Deckgl.svelte file, I did `export let deck`. In my main app file I did the following using an input: 

```
<script>
...
function dataChange() {
  hex.setProps({layers: [layers()] })
}
</script>
<SvelteDeckGL layers={layers2} {viewState} {getTooltip} TOKEN={MAPBOX_TOKEN} bind:deck={hex} />
```

This then updated the data. There are otherways to do two way binding eg. dispatch.

I hope this helps?

Ryan

**Comment by arperyan** [comment]
No feedback
